language: node_js
node_js:
- '6'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
- npm prune
after_success:
- npm run semantic-release
deploy:
  provider: npm
  email: contact@trekkingforcharity.org
  api_key:
    secure: r1E6zOgzMER336rfOdk+XpypZ+LDaaUM2y7luynNpTEtueK9JvHe5Kb8TpF3ZG4yDj0qNQbhDPwo2cJ100TO4vOfjjdFa8gi0l0j0vzdAgzSDerdMl43A+Ti1oT4eQz19BjX8TiIec/HKXk183sWD2vaBf6NB4cHGBszUF6YjEP4UOGORbg7UPR7FMH6qI3zYHc7Nv2Jm9fTvHSvygELJ7lRM37xVzMzBU3bZecjkbRoNkfNLu4LdCFj5beRVO097iygnERkyqKFSUrudZJSGNh2ouc7r8k+dSvnMqwD0NcSaLe8RLWPOacSfbLRHsltwtGqrpPL24OdeEwGSgSN1z96GeWc2GMTUbVWwaCUfvppJZXZaOZpcD+6bXxJeI9laljnKzOatvXn1fTWQEIcg7rAnnoe6qSVlWgnMtw099zr9ubJg4fYisbCSS82GZFB0ujLAS7CLQkAEBHMOabivdTqcS4+wTQ6FrA2XZj4yZCUO5zxuPuLOucxGJC2SGVx/94/U4VEBqkpNTYcBVVXxAVzPkGJNEaIaGkwcgQ7KiEA0f5V0VtxuKBnGNWEfn3NcRBgxv4Ay0H1W8lVfD6yCTFHZZEB+HJrpAEJsaHbf1SIZnoJEk4tYBnusCo8QPW1dnnlwIe18TkE6ctv8of92Pai2YsDd/r8MiKxcLWzmYc=
  on:
    tags: true
    repo: TrekkingForCharity/ts-odata
